#!/bin/sh

echo "FileSystem Patching Tool"
echo "========================"
echo
echo "This tool will patch the file system with the latest changes."
echo
echo "$(tput setaf 3)Warning: This will overwrite existing files in the / directory.$(tput sgr0)"
echo
echo "You must be root to run this script."
echo
echo "$(tput setaf 4)You are responsible for any changes made to the file system. Take in mind what you are doing before proceeding.$(tput sgr0)"
echo "$(tput setaf 1)_____________________________________________$(tput sgr0)"
echo "$(tput setaf 1)$(tput bold)Press Enter to continue and CTRL+C to cancel.$(tput sgr0)"
read -r

mkdir ~/.newFS
cd ~/.newFS

git clone --recurse-submodules https://github.com/lucasengithub/OSFS

cp -rvf ~/.newFS/OSFS/common/* /
cp -rvf ~/.newFS/OSFS/common/.[^.]* / 2>/dev/null || true
echo
echo "$(tput setaf 2)File system patched$(tput sgr0)"
rm -rf ~/.newFS

chmod +x /System/Commands/Utils/*
source /etc/profile
