#!/bin/sh

# Check for --nsm option
NSM_MODE=false
if [ "$1" = "--nsm" ]; then
    NSM_MODE=true
fi

echo "FileSystem Patching Tool"
echo "========================"
echo
if [ "$NSM_MODE" = true ]; then
    echo "This tool will patch the file system with the latest changes (without submodules)."
else
    echo "This tool will patch the file system with the latest changes including items from the submodules."
fi
echo "If you don't want to clone the submodules, you can run this script with the --nsm option."
echo
echo "$(tput setaf 3)Warning: This will overwrite existing files in the / directory.$(tput sgr0)"
echo
echo "You must be root to run this script."
echo
echo "$(tput setaf 4)You are responsible for any changes made to the file system. Take in mind what you are doing before proceeding.$(tput sgr0)"
echo "$(tput setaf 1)_____________________________________________$(tput sgr0)"
echo "$(tput setaf 1)$(tput bold)Press Enter to continue and CTRL+C to cancel.$(tput sgr0)"
read -r

mkdir ~/.newFS
cd ~/.newFS

if [ "$NSM_MODE" = true ]; then
    echo "$(tput setaf 6)Cloning ostree without submodules...$(tput sgr0)"
    git clone https://github.com/lucasengithub/OSFS
else
    echo "$(tput setaf 6)Cloning ostree with submodules...$(tput sgr0)"
    git clone --recurse-submodules https://github.com/lucasengithub/OSFS
fi

cp -rvf ~/.newFS/OSFS/common/* /
cp -rvf ~/.newFS/OSFS/common/.[^.]* / 2>/dev/null || true
echo
echo "$(tput setaf 2)File system patched$(tput sgr0)"
rm -rf ~/.newFS

chmod +x /System/Commands/Utils/*
chmod +x /System/Developer/GenOSToolkit/*
source /etc/profile

