#!/bin/sh
echo
echo "Generate System Image"
echo "======================"
echo
echo "This tool creates a system image from the current system state to be used for booting."
echo
echo "$(tput setaf 3)Warning: This will overwrite existing files in the /Out directory.$(tput sgr0)"
echo
echo "You must be root to run this script."
echo
echo "$(tput setaf 4)You are responsible for any changes made to the file system. Ensure you know what you are doing before proceeding.$(tput sgr0)"
echo "$(tput setaf 1)_____________________________________________$(tput sgr0)"
echo "$(tput setaf 1)$(tput bold)Press Enter to continue and CTRL+C to cancel.$(tput sgr0)"
read -r
echo
echo "$(tput setaf 2)Creating system image...$(tput sgr0)"
rm -fr /Out
mkdir -p /Out
mksquashfs / /Out/CurrentState.system -e boot home root Users Out proc sys dev tmp run var/tmp var/run var/lock mnt media lost+found
echo "$(tput setaf 2)System image created at /Out/CurrentState.system$(tput sgr0)"
echo
echo "$(tput setaf 2)Activate the image changing the name to a suitable slot name before using it. (a.system, b.system, etc.)$(tput sgr0)"
echo
echo "Use 'updateab' to do that."
echo
echo bye
echo
