#!/bin/sh

echo "Regenerate Home Skeleton Tool"
echo "============================="
echo
echo "This tool clone the skeleton directory for a new user in your current home directory."
echo
echo "$(tput setaf 3)Warning: Some data will be lost during the cloning process.$(tput sgr0)"
echo
echo "$(tput setaf 4)You are responsible for any changes made to the file system. Take in mind what you are doing before proceeding.$(tput sgr0)"
echo "$(tput setaf 1)_____________________________________________$(tput sgr0)"
echo "$(tput setaf 1)$(tput bold)Press Enter to continue and CTRL+C to cancel.$(tput sgr0)"
read -r

cp -rvf /etc/skel/* ~/
cp -rvf /etc/skel/.[^.]* ~/ 2>/dev/null || true
echo
echo "$(tput setaf 2)Home skeleton regenerated$(tput sgr0)"
echo 
echo "$(tput setaf 6)You may need to log out and log in again to see the changes.$(tput sgr0)" 
