#!/bin/sh

# Flatpak force user installation 


if [ "$1" = "install" ]; then
    pkg="${@: -1}"
    found=0
    for arg in "$@"; do
        if [ "$arg" = "remote-add" ]; then
            found=1
            break
        fi
    done
    if [ $found -eq 0 ]; then
        flatpak remote-add --if-not-exists --user flathub "$pkg"
    fi
fi
flatpak "$@"